- name: "Run all role tasks for Ubuntu"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    cfg_cron_system_packages: "{{ cfg_cron_ubuntu_packages }}"
    cfg_cron_system_service: "{{ cfg_cron_ubuntu_service }}"
  when: ansible_distribution == "Ubuntu"

- name: "Run all role tasks for Arch Linux"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    cfg_cron_system_packages: "{{ cfg_cron_archlinux_packages }}"
    cfg_cron_system_service: "{{ cfg_cron_archlinux_service }}"
  when: ansible_os_family == "Archlinux"

- name: "Run all role tasks for FreeBSD"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    cfg_cron_system_packages: "{{ cfg_cron_freebsd_packages }}"
    cfg_cron_system_service: "{{ cfg_cron_freebsd_service }}"
  when: ansible_os_family == "FreeBSD"

